# Default values for jellyfin-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jellyfin:
  replicaCount: 1

  name: jellyfin
  timezone: America/New_York

  image:
    repository: ghcr.io/aleksasiriski/jellyfin-rffmpeg
    pullPolicy: IfNotPresent
    tag: latest

  service:
    enabled: true
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}

    hosts:
      - chart-example.local 
    path: /

  extraVolumeMounts: []
  extraVolumes: []

rffmpeg:
  replicaCount: 3

  name: rffmpeg
  timezone: America/New_York

  image:
    repository: ghcr.io/aleksasiriski/rffmpeg-worker
    pullPolicy: IfNotPresent
    tag: latest

  service:
    enabled: true
    name: rffmpeg-workers
    type: ClusterIP
    port: 22

  extraVolumeMounts: []
  extraVolumes: []

persistence:
  config:
    enabled: true
    accessMode: ReadWriteMany
    className: longhorn
    size: 10Gi
  subtitles:
    enabled: false
    accessMode: ReadWriteMany
    className: longhorn
    size: 10Gi
  transcodes:
    enabled: false
    accessMode: ReadWriteMany
    className: longhorn
    size: 30Gi
  media:
    enabled: false
    accessMode: ReadWriteMany
    className: longhorn
    size: 10Gi
