{{- with .Values.jellyfin }}
  {{- if .service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .service.type }}
          {{- if .service.clusterIP }}
  clusterIP: {{ .service.clusterIP }}
          {{- end }}
  ports:
    - port: {{ .service.port }}
      targetPort: jellyfin-http
      protocol: TCP
      name: jellyfin-http
  selector:
    app: {{ .name }}
  {{- end -}}
{{- end -}}
